/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RestaurantGUI;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ngsm
 */
public class OrderListWindow extends javax.swing.JDialog {

    private Order theOrder;
    private Restaurant theRestaurant;
    private MenuItem theMenuItem;
    private DefaultListModel listModel;

    /**
     * Creates new form OrderListWindow
     */
    public OrderListWindow(java.awt.Frame parent, boolean modal, Order theOrder) {
        super(parent, modal);
        this.theOrder = theOrder;
        this.theRestaurant = ((RestaurantGUI) parent).getRestaurant();
        initComponents();
        tableNoLabel.setText("Table No: " + theOrder.getTheTable().getTableNo());
        orderNoLabel.setText("Order No: " + theOrder.getOrderNo());
        listModel = new DefaultListModel();
        orderList.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        tableNoLabel = new javax.swing.JLabel();
        orderNoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        itemNoTF = new javax.swing.JTextField();
        menuItemLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        qtyCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        requestTF = new javax.swing.JTextField();
        addItemButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderList = new javax.swing.JList();
        cancelButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableNoLabel.setText("Table No: ");

        orderNoLabel.setText("Order No:");

        jLabel1.setText("Item No");

        itemNoTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                itemNoTFFocusLost(evt);
            }
        });
        itemNoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNoTFActionPerformed(evt);
            }
        });

        menuItemLabel.setText("menu item description");

        jLabel2.setText("Quantity");

        qtyCombo.setEditable(true);
        qtyCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        jLabel3.setText("Special Request");

        addItemButton.setText("Add Item");
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Ordered Items:");

        orderList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(orderList);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        confirmButton.setText("Confirm Order");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete Selected Items");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        totalLabel.setText("Order Total : $0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(requestTF, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(addItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel4)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tableNoLabel)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                    .addGap(38, 38, 38)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(qtyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(itemNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(36, 36, 36)
                                            .addComponent(menuItemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGap(56, 56, 56)
                            .addComponent(orderNoLabel)
                            .addGap(40, 40, 40)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addGap(97, 97, 97))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(totalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton)
                    .addComponent(confirmButton))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableNoLabel)
                    .addComponent(orderNoLabel))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(menuItemLabel)
                    .addComponent(itemNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(qtyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(requestTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addItemButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(totalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(confirmButton))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemNoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNoTFActionPerformed

    private void itemNoTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemNoTFFocusLost

        // TODO add your handling code here:
        String itemStr = itemNoTF.getText();
        if (!itemStr.equals("")) {
            int itemNo = Integer.parseInt(itemStr);
            theMenuItem = theRestaurant.findMenuItem(itemNo);
            if (theMenuItem != null) {
                menuItemLabel.setText(theMenuItem.getDescription());
                menuItemLabel.setForeground(Color.BLUE);
            } else {
                menuItemLabel.setText("Menu Item not found!");
                menuItemLabel.setForeground(Color.RED);
            }
        }
    }//GEN-LAST:event_itemNoTFFocusLost

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        // TODO add your handling code here:
        int qty = Integer.parseInt((String) qtyCombo.getSelectedItem());
        String req = requestTF.getText();
        OrderItem oi = theOrder.addItem(theMenuItem, qty, req);
        if (oi == null) // item already exists
        {
            JOptionPane.showMessageDialog(this, "Item already ordered. Delete to change", "error", JOptionPane.ERROR_MESSAGE);
        } else {
            listModel.addElement(oi);
            theMenuItem = null;
            itemNoTF.setText("");
            qtyCombo.setSelectedIndex(0);
            requestTF.setText("");
            updateOrderTotal();
        }
    }//GEN-LAST:event_addItemButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        java.util.List<OrderItem> unwanted;
        unwanted = orderList.getSelectedValuesList();
        for (OrderItem ui : unwanted) {
            theOrder.removeItem(ui);
            listModel.removeElement(ui);
        }
        updateOrderTotal();
    
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(this,"Confirm cancel order#" + theOrder.getOrderNo() +"?",
                "Cancel Order", JOptionPane.YES_NO_OPTION);
        if (opt == JOptionPane.YES_OPTION)
        {
            theOrder.setStatus("Cancelled");
            this.dispose();
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        theOrder.setStatus("Confirmed");
        JOptionPane.showMessageDialog(this, "Order Number :" + theOrder.getOrderNo() + " is confirmed");
        this.dispose();
    }//GEN-LAST:event_confirmButtonActionPerformed

// a method to update the label
private void updateOrderTotal()
    {
        double totalPrice = theOrder.getTotal();
        String result = String.format("Order Total :$%.2f",totalPrice);
        totalLabel.setText(result);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField itemNoTF;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel menuItemLabel;
    private javax.swing.JList orderList;
    private javax.swing.JLabel orderNoLabel;
    private javax.swing.JComboBox<String> qtyCombo;
    private javax.swing.JTextField requestTF;
    private javax.swing.JLabel tableNoLabel;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
